package enums;

public enum Command {
    OPEN, SAVE,
    VIEW_ORIGINAL, VIEW_FILTERED,
    ROTATE, RESIZE,
    GRAYSCALE, INVERT, SMOOTHING, SHARPEN, EMBOSS, GAMMA,
    ROBERTS, SOBEL,
    DITHERING, ORDERED_DITHERING,
    WATERCOLOR
}
